spring:
  application:
    name: projectmodule2lms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meat4
    username: root
    password: 1234

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
